spring:
  application:
    name: CompMathLab4
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./1
    driverClassName: org.h2.Driver

bot:
  name:  ${BOT_NAME}
  token: ${BOT_TOKEN}

rabbitmq:
  to_solve: ${RABBITMQ_QUEUE_TO_SOLVE}
  to_response: ${RABBITMQ_QUEUE_TO_RESPONSE}
  to_graph: ${RABBITMQ_QUEUE_TO_GRAPH}
  from_graph:  ${RABBITMQ_QUEUE_FROM_GRAPH}